import { ServiceItem, WebhookConfig } from "./types";

export const allServices: ServiceItem[] = [
  {
    name: "Regular Cleaning",
    slug: "regular-cleaning",
    icon: "🧹",
    category: "Domestic",
    description: "Routine maintenance for a clean, consistent living environment (Fantastic & Jim's style).",
    baseRatePerHour: 45,
    rating: 4.9,
    durationEstimateHours: 3,
  },
  {
    name: "Commercial Cleaning",
    slug: "commercial-cleaning",
    icon: "🏢",
    category: "Commercial",
    description: "Enterprise-grade office complexes, retail, and corporate facilities under ISO WHS guidelines.",
    baseRatePerHour: 48,
    rating: 4.9,
    durationEstimateHours: 4,
  },
  {
    name: "Office Cleaning",
    slug: "office-cleaning",
    icon: "💼",
    category: "Commercial",
    description: "Scheduled high-frequency sanitation of workstations, boardrooms, and communal breakrooms.",
    baseRatePerHour: 42,
    rating: 4.8,
    durationEstimateHours: 3,
  },
  {
    name: "Carpet Cleaning",
    slug: "carpet-cleaning",
    icon: "🧹",
    category: "Specialised",
    description: "Deep hot-water steam extraction, commercial stain removal, and fibre conditioning.",
    baseRatePerHour: 65,
    rating: 4.7,
    durationEstimateHours: 2,
  },
  {
    name: "Tile & Grout",
    slug: "tile-grout-cleaning",
    icon: "🧱",
    category: "Specialised",
    description: "High-pressure dynamic scrubbing, grout acid washing, and protective hydrophobic coating.",
    baseRatePerHour: 70,
    rating: 4.6,
    durationEstimateHours: 3,
  },
  {
    name: "Window Cleaning",
    slug: "window-cleaning",
    icon: "🪟",
    category: "Specialised",
    description: "Deionised water reach-pole exterior wash, safety harness high-rise, and interior glass polishing.",
    baseRatePerHour: 55,
    rating: 4.5,
    durationEstimateHours: 3,
  },
  {
    name: "Pressure Cleaning",
    slug: "pressure-cleaning",
    icon: "💦",
    category: "Specialised",
    description: "Heavy machinery washdown, concrete driveways, brick masonry scaling, and stain blasting.",
    baseRatePerHour: 80,
    rating: 4.9,
    durationEstimateHours: 2,
  },
  {
    name: "NDIS Cleaning",
    slug: "ndis-cleaning",
    icon: "♿",
    category: "Domestic",
    description: "Fully registered NDIS support-compliant household hygiene, regular carer-compatible maintenance.",
    baseRatePerHour: 45,
    rating: 4.95,
    durationEstimateHours: 3,
  },
  {
    name: "End of Lease",
    slug: "end-of-lease-cleaning",
    icon: "🔑",
    category: "Domestic",
    description: "100% Bond Back guarantee coverage of domestic and corporate tenancy exit specifications.",
    baseRatePerHour: 50,
    rating: 4.85,
    durationEstimateHours: 6,
  },
  {
    name: "Builders Cleaning",
    slug: "builders-cleaning",
    icon: "🏗️",
    category: "Specialised",
    description: "Post-construction dust filtration, silica protective control, premium detailing finishes.",
    baseRatePerHour: 85,
    rating: 4.75,
    durationEstimateHours: 8,
  },
  {
    name: "Upholstery Cleaning",
    slug: "upholstery-cleaning",
    icon: "🛋️",
    category: "Specialised",
    description: "Fabric, commercial seating, and high-quality leather steam sanitation and stain shield.",
    baseRatePerHour: 60,
    rating: 4.65,
    durationEstimateHours: 2,
  },
  {
    name: "Bathroom Sanitising",
    slug: "bathroom-cleaning",
    icon: "Shower",
    category: "Commercial",
    description: "Heavy chemical wash, microbial disinfectant coating, deep-drain cleaning and replenishment.",
    baseRatePerHour: 42,
    rating: 4.4,
    durationEstimateHours: 1.5,
  },
  {
    name: "Kitchen Deep-Clean",
    slug: "kitchen-cleaning",
    icon: "🍳",
    category: "Commercial",
    description: "HACCP compliant kitchen sanitation, extraction canopy steam, flat-top carbon scraping.",
    baseRatePerHour: 58,
    rating: 4.8,
    durationEstimateHours: 4,
  }
];

export const demoPostcodes = ["6000", "6004", "6005", "6007", "6008", "6009", "6010", "6019", "6027", "6160", "6210", "2000", "3000", "4000", "5000", "7000", "8000"];

export const defaultWebhookConfig: WebhookConfig = {
  webhookUrl: "https://api.aastaclean.com/v1/quotes",
  headerName: "X-AASTACLEAN-CRM-KEY",
  headerValue: "aasta_secret_bearer_926600",
  crmType: "Zapier",
  triggerOnQuote: true,
  triggerOnSearch: true,
  isActive: true,
};
